### ISSUE TITLE
neovim plugin: nvim-jqx

### ISSUE THREAD

**Issue by gennaro-tedesco** [burningtree/awesome-json#74]
I would like to propose [nvim-jqx](https://github.com/gennaro-tedesco/nvim-jqx), a neovim plugin I have written to browse and operate on json files. I have seen an equivalent Vim plugin is listed thus I thought I would suggest the equivalent for neovim.

Let me know if you deem useful to add it and if so I might open a PR.

**Comment by burningtree** [comment]
Hello, it looks useful. Waiting for PR :)

**Comment by gennaro-tedesco** [comment]
Great, I have created https://github.com/burningtree/awesome-json/pull/75
